export const colorPalette = [
    { colorName: 'Blue', hexCode: '#0088FE' },
    { colorName: 'Green', hexCode: '#00C49F' },
    { colorName: 'Yellow', hexCode: '#FFBB28' },
    { colorName: 'Orange', hexCode: '#FF8042' },
    { colorName: 'Purple', hexCode: '#8884D8' },
    { colorName: 'Red', hexCode: '#FF0000' },
    { colorName: 'Pink', hexCode: '#FFC0CB' },
    { colorName: 'Teal', hexCode: '#008080' },
    { colorName: 'Gold', hexCode: '#FFD700' },
    { colorName: 'Indigo', hexCode: '#4B0082' },
    { colorName: 'Cyan', hexCode: '#00FFFF' },
    { colorName: 'Magenta', hexCode: '#FF00FF' },
    { colorName: 'Lime', hexCode: '#00FF00' },
    { colorName: 'Dark Blue', hexCode: '#00008B' },
    { colorName: 'Brown', hexCode: '#A52A2A' },
    { colorName: 'Slate Gray', hexCode: '#708090' },
    { colorName: 'Coral', hexCode: '#FF7F50' },
    { colorName: 'Mint', hexCode: '#98FF98' },
    { colorName: 'Lavender', hexCode: '#E6E6FA' },
    { colorName: 'Crimson', hexCode: '#DC143C' },
    { colorName: 'Dark Orange', hexCode: '#FF8C00' },
    { colorName: 'Steel Blue', hexCode: '#4682B4' },
    { colorName: 'Khaki', hexCode: '#F0E68C' },
    { colorName: 'Salmon', hexCode: '#FA8072' },
    { colorName: 'Olive', hexCode: '#808000' },
    { colorName: 'Dark Green', hexCode: '#006400' },
    { colorName: 'Sky Blue', hexCode: '#87CEEB' },
    { colorName: 'Sea Green', hexCode: '#2E8B57' },
];